package com.gmmd.bss.dom.cm;

import com.gmmd.bss.dom.DomObject;

/**
 * ComMasGenericLov generated by hbm2java
 */
public class MasGenericLov  extends DomObject {

	private static final long serialVersionUID = 1L;
	
	private Integer lovId;
	private String name;
	private String value;
	private String category;
	private String caption;

	public MasGenericLov() {
	}

	public MasGenericLov(Integer lovId, String name, String value,
			String category) {
		this.lovId = lovId;
		this.name = name;
		this.value = value;
		this.category = category;
	}

	public MasGenericLov(Integer lovId, String name, String value,
			String category, String caption) {
		this.lovId = lovId;
		this.name = name;
		this.value = value;
		this.category = category;
		this.caption = caption;
	}

	public Integer getLovId() {
		return lovId;
	}

	public void setLovId(Integer lovId) {
		this.lovId = lovId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCaption() {
		return caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

}
