package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gmmd.bss.dom.DomObject;

/**
 * CampaignConditionParam generated by hbm2java
 */
public class CampaignConditionParam extends DomObject {

	private static final long serialVersionUID = 1L;
	
	private Integer campaignCondParamId;
	private MasCouponTypeParam masCouponTypeParam;
	private CouponCampaign couponCampaign;
	private String condParamName;
	private String condParamValue;
	private String status;

	public CampaignConditionParam() {
	}

	public CampaignConditionParam(Integer campaignCondParamId,
			String condParamName, String condParamValue, String status,
			Date createDate, String createBy) {
		this.campaignCondParamId = campaignCondParamId;
		this.condParamName = condParamName;
		this.condParamValue = condParamValue;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public CampaignConditionParam(int campaignCondParamId,
			MasCouponTypeParam masCouponTypeParam,
			CouponCampaign couponCampaign, String condParamName,
			String condParamValue, String status, Date createDate,
			String createBy, Date updateDate, String updateBy) {
		this.campaignCondParamId = campaignCondParamId;
		this.masCouponTypeParam = masCouponTypeParam;
		this.couponCampaign = couponCampaign;
		this.condParamName = condParamName;
		this.condParamValue = condParamValue;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public Integer getCampaignCondParamId() {
		return campaignCondParamId;
	}

	public void setCampaignCondParamId(Integer campaignCondParamId) {
		this.campaignCondParamId = campaignCondParamId;
	}

	public MasCouponTypeParam getMasCouponTypeParam() {
		return masCouponTypeParam;
	}

	public void setMasCouponTypeParam(MasCouponTypeParam masCouponTypeParam) {
		this.masCouponTypeParam = masCouponTypeParam;
	}

	public CouponCampaign getCouponCampaign() {
		return couponCampaign;
	}

	public void setCouponCampaign(CouponCampaign couponCampaign) {
		this.couponCampaign = couponCampaign;
	}

	public String getCondParamName() {
		return condParamName;
	}

	public void setCondParamName(String condParamName) {
		this.condParamName = condParamName;
	}

	public String getCondParamValue() {
		return condParamValue;
	}

	public void setCondParamValue(String condParamValue) {
		this.condParamValue = condParamValue;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
