package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gmmd.bss.dom.DomObject;

/**
 * CouponUsage generated by hbm2java
 */
public class CouponUsage extends DomObject{

	private static final long serialVersionUID = 1L;
	
	private Integer couponUsageId;
	private Coupon coupon;
	private String passCode;
	private String extCusId;
	private String extSystemId;
	private Date usageDate;
	private String extRefOpt1;
	private String extRefOpt2;
	private String extRefOpt3;
	private String remark;
	private String status;

	public CouponUsage() {}

	public CouponUsage(Integer couponUsageId, String extCusId, String extSystemId,
			Date usageDate, String status, Date createDate, String createBy) {
		this.couponUsageId = couponUsageId;
		this.extCusId = extCusId;
		this.extSystemId = extSystemId;
		this.usageDate = usageDate;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public CouponUsage(Integer couponUsageId, Coupon coupon, String passCode,
			String extCusId, String extSystemId, Date usageDate,
			String extRefOpt1, String extRefOpt2, String extRefOpt3, String remark,
			String status, Date createDate, String createBy, Date updateDate,
			String updateBy) {
		this.couponUsageId = couponUsageId;
		this.coupon = coupon;
		this.passCode = passCode;
		this.extCusId = extCusId;
		this.extSystemId = extSystemId;
		this.usageDate = usageDate;
		this.extRefOpt1= extRefOpt1;
		this.extRefOpt2= extRefOpt2;
		this.extRefOpt3= extRefOpt3;
		this.remark = remark;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public Integer getCouponUsageId() {
		return couponUsageId;
	}

	public void setCouponUsageId(Integer couponUsageId) {
		this.couponUsageId = couponUsageId;
	}

	public Coupon getCoupon() {
		return coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}
	
	public String getPassCode() {
		return passCode;
	}

	public void setPassCode(String passCode) {
		this.passCode = passCode;
	}

	public String getExtCusId() {
		return extCusId;
	}

	public void setExtCusId(String extCusId) {
		this.extCusId = extCusId;
	}

	public String getExtSystemId() {
		return extSystemId;
	}

	public void setExtSystemId(String extSystemId) {
		this.extSystemId = extSystemId;
	}

	public Date getUsageDate() {
		return usageDate;
	}

	public void setUsageDate(Date usageDate) {
		this.usageDate = usageDate;
	}

	public String getExtRefOpt1() {
		return extRefOpt1;
	}

	public void setExtRefOpt1(String extRefOpt1) {
		this.extRefOpt1 = extRefOpt1;
	}

	public String getExtRefOpt2() {
		return extRefOpt2;
	}

	public void setExtRefOpt2(String extRefOpt2) {
		this.extRefOpt2 = extRefOpt2;
	}

	public String getExtRefOpt3() {
		return extRefOpt3;
	}

	public void setExtRefOpt3(String extRefOpt3) {
		this.extRefOpt3 = extRefOpt3;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
