package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gmmd.bss.dom.DomObject;

/**
 * CouponCampaign generated by hbm2java
 */
public class CouponCampaign extends DomObject {

	private static final long serialVersionUID = 1L;
	
	private Integer couponCampaignId;
	private UsageChannel usageChannel;
	private Org orgByPartnerId;
	private Org orgByCreaterId;
	private CouponType couponType;
	private String campaignName;
	private String prefixCode;
	private String suffixCode;
	private Integer validOn;
	private Date startDate;
	private Date endDate;
	private String description;
	private String status;
	private List<Coupon> coupons = new ArrayList<Coupon>(0);
	private List<CampaignConditionParam> campaignConditionParams = new ArrayList<CampaignConditionParam>(0);

	public CouponCampaign() {
	}

	public CouponCampaign(int couponCampaignId, String status,
			Date createDate, String createBy) {
		this.couponCampaignId = couponCampaignId;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public CouponCampaign(Integer couponCampaignId,
			UsageChannel usageChannel, Org orgByPartnerId,
			Org orgByCreaterId, CouponType couponType,
			String campaignName, String prefixCode, String suffixCode,
			Integer validOn, Date startDate, Date endDate, String description,
			String status, Date createDate, String createBy, Date updateDate,
			String updateBy, List<Coupon> coupons, List<CampaignConditionParam> campaignConditionParams) {
		this.couponCampaignId = couponCampaignId;
		this.usageChannel = usageChannel;
		this.orgByPartnerId = orgByPartnerId;
		this.orgByCreaterId = orgByCreaterId;
		this.couponType = couponType;
		this.campaignName = campaignName;
		this.prefixCode = prefixCode;
		this.suffixCode = suffixCode;
		this.validOn = validOn;
		this.startDate = startDate;
		this.endDate = endDate;
		this.description = description;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.coupons = coupons;
		this.campaignConditionParams = campaignConditionParams;
	}

	public Integer getCouponCampaignId() {
		return couponCampaignId;
	}

	public void setCouponCampaignId(Integer couponCampaignId) {
		this.couponCampaignId = couponCampaignId;
	}

	public UsageChannel getUsageChannel() {
		return usageChannel;
	}

	public void setUsageChannel(UsageChannel usageChannel) {
		this.usageChannel = usageChannel;
	}

	public Org getOrgByPartnerId() {
		return orgByPartnerId;
	}

	public void setOrgByPartnerId(Org orgByPartnerId) {
		this.orgByPartnerId = orgByPartnerId;
	}

	public Org getOrgByCreaterId() {
		return orgByCreaterId;
	}

	public void setOrgByCreaterId(Org orgByCreaterId) {
		this.orgByCreaterId = orgByCreaterId;
	}

	public CouponType getCouponType() {
		return couponType;
	}

	public void setCouponType(CouponType couponType) {
		this.couponType = couponType;
	}

	public String getCampaignName() {
		return campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	public String getPrefixCode() {
		return prefixCode;
	}

	public void setPrefixCode(String prefixCode) {
		this.prefixCode = prefixCode;
	}

	public String getSuffixCode() {
		return suffixCode;
	}

	public void setSuffixCode(String suffixCode) {
		this.suffixCode = suffixCode;
	}

	public Integer getValidOn() {
		return validOn;
	}

	public void setValidOn(Integer validOn) {
		this.validOn = validOn;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<Coupon> getCoupons() {
		return coupons;
	}

	public void setCoupons(List<Coupon> coupons) {
		this.coupons = coupons;
	}

	public List<CampaignConditionParam> getCampaignConditionParams() {
		return campaignConditionParams;
	}

	public void setCampaignConditionParams(
			List<CampaignConditionParam> campaignConditionParams) {
		this.campaignConditionParams = campaignConditionParams;
	}
}
