package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gmmd.bss.dom.DomObject;

/**
 * Coupon generated by hbm2java
 */
public class Coupon extends DomObject {

	private static final long serialVersionUID = 1L;
	
	private Integer couponId;
	private CouponCampaign couponCampaign;
	private String couponCode;
	private String couponFullCode;
	private Integer limitUsageCount;
	private Integer numberOfUsage;
	private Date startDate;
	private Date endDate;
	private String remark;
	private String status;
	private List<CouponUsage> couponUsages = new ArrayList<CouponUsage>(0);

	public Coupon() {
	}

	public Coupon(Integer couponId, String couponCode, Integer limitUsageCount,
			String status, Date createDate, String createBy) {
		this.couponId = couponId;
		this.couponCode = couponCode;
		this.limitUsageCount = limitUsageCount;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public Coupon(Integer couponId, CouponCampaign couponCampaign,
			String couponCode, String couponFullCode, Integer limitUsageCount,
			Integer numberOfUsage, Date startDate, Date endDate
			, String remark, String status, Date createDate
			, String createBy, Date updateDate, String updateBy
			, List<CouponUsage> couponUsages) {
		this.couponId = couponId;
		this.couponCampaign = couponCampaign;
		this.couponCode = couponCode;
		this.couponFullCode = couponFullCode;
		this.limitUsageCount = limitUsageCount;
		this.numberOfUsage = numberOfUsage;
		this.startDate = startDate;
		this.endDate = endDate;
		this.remark = remark;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.couponUsages = couponUsages;
	}

	public Integer getCouponId() {
		return couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	public CouponCampaign getCouponCampaign() {
		return couponCampaign;
	}

	public void setCouponCampaign(CouponCampaign couponCampaign) {
		this.couponCampaign = couponCampaign;
	}

	public String getCouponCode() {
		return couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	public String getCouponFullCode() {
		return couponFullCode;
	}

	public void setCouponFullCode(String couponFullCode) {
		this.couponFullCode = couponFullCode;
	}

	public Integer getLimitUsageCount() {
		return limitUsageCount;
	}

	public void setLimitUsageCount(Integer limitUsageCount) {
		this.limitUsageCount = limitUsageCount;
	}

	public Integer getNumberOfUsage() {
		return numberOfUsage;
	}

	public void setNumberOfUsage(Integer numberOfUsage) {
		this.numberOfUsage = numberOfUsage;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<CouponUsage> getCouponUsages() {
		return couponUsages;
	}

	public void setCouponUsages(List<CouponUsage> couponUsages) {
		this.couponUsages = couponUsages;
	}

}
