package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gmmd.bss.dom.DomObject;

/**
 * MasCouponTypeParam generated by hbm2java
 */
public class MasCouponTypeParam extends DomObject {
	
	private static final long serialVersionUID = 1L;
	
	private Integer couponTypeParamId;
	private CouponEventProcess couponEventProcess;
	private CouponType couponType;
	private String paramName;
	private String status;
	private List<CampaignConditionParam> campaignConditionParams = new ArrayList<CampaignConditionParam>(0);

	public MasCouponTypeParam() {}

	public MasCouponTypeParam(Integer couponTypeParamId, String paramName,
			String status, Date createDate, String createBy) {
		this.couponTypeParamId = couponTypeParamId;
		this.paramName = paramName;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public MasCouponTypeParam(Integer couponTypeParamId,
			CouponEventProcess couponEventProcess,
			CouponType couponType, String paramName, String status,
			Date createDate, String createBy, Date updateDate, String updateBy,
			List<CampaignConditionParam> campaignConditionParams) {
		this.couponTypeParamId = couponTypeParamId;
		this.couponEventProcess = couponEventProcess;
		this.couponType = couponType;
		this.paramName = paramName;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.campaignConditionParams = campaignConditionParams;
	}

	public Integer getCouponTypeParamId() {
		return couponTypeParamId;
	}

	public void setCouponTypeParamId(Integer couponTypeParamId) {
		this.couponTypeParamId = couponTypeParamId;
	}

	public CouponEventProcess getCouponEventProcess() {
		return couponEventProcess;
	}

	public void setCouponEventProcess(CouponEventProcess couponEventProcess) {
		this.couponEventProcess = couponEventProcess;
	}

	public CouponType getCouponType() {
		return couponType;
	}

	public void setCouponType(CouponType couponType) {
		this.couponType = couponType;
	}

	public String getParamName() {
		return paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<CampaignConditionParam> getCampaignConditionParams() {
		return campaignConditionParams;
	}

	public void setCampaignConditionParams(
			List<CampaignConditionParam> campaignConditionParams) {
		this.campaignConditionParams = campaignConditionParams;
	}

}
