package com.gmmd.bss.dom.cpn;

// Generated 1 ��.�. 2558, 11:22:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gmmd.bss.dom.DomObject;

/**
 * Org generated by hbm2java
 */
public class Org extends DomObject {

	private static final long serialVersionUID = 1L;
	
	private Integer orgId;
	private String orgCode;
	private String orgName;
	private String address;
	private String contact;
	private String email;
	private String description;
	private String status;
	private List<CouponCampaign> campaignsForCreaterIds = new ArrayList<CouponCampaign>(0);
	private List<CouponCampaign> campaignsForPartnerIds = new ArrayList<CouponCampaign>(0);

	public Org() {}

	public Org(Integer orgId, String orgName, String status, Date createDate,
			String createBy) {
		this.orgId = orgId;
		this.orgName = orgName;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public Org(Integer orgId, String orgCode, String orgName, String address,
			String contact, String email, String description, String status,
			Date createDate, String createBy, Date updateDate, String updateBy,
			List<CouponCampaign> campaignsForCreaterIds,
			List<CouponCampaign> campaignsForPartnerIds) {
		this.orgId = orgId;
		this.orgCode = orgCode;
		this.orgName = orgName;
		this.address = address;
		this.contact = contact;
		this.email = email;
		this.description = description;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.campaignsForCreaterIds = campaignsForCreaterIds;
		this.campaignsForPartnerIds = campaignsForPartnerIds;
	}

	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<CouponCampaign> getCampaignsForCreaterIds() {
		return campaignsForCreaterIds;
	}

	public void setCampaignsForCreaterIds(
			List<CouponCampaign> campaignsForCreaterIds) {
		this.campaignsForCreaterIds = campaignsForCreaterIds;
	}

	public List<CouponCampaign> getCampaignsForPartnerIds() {
		return campaignsForPartnerIds;
	}

	public void setCampaignsForPartnerIds(
			List<CouponCampaign> campaignsForPartnerIds) {
		this.campaignsForPartnerIds = campaignsForPartnerIds;
	}

}
